package btpos.source.vdfdsl.tf2.filegeneration.representations

import btpos.source.vdfdsl.tf2.filegeneration.camelCase
import btpos.source.vdfdsl.tf2.filegeneration.representations.NamedAttribute.EffectType
import btpos.source.vdfdsl.tf2.filegeneration.representations.groupings.NamedAttributeScope
import btpos.source.vdfdsl.tf2.filegeneration.representations.groupings.PenaltyBonus
import btpos.source.vdfdsl.tf2.filegeneration.representations.groupings.Vis
import java.lang.ProcessBuilder.Redirect.to
import javax.management.Query.attr
import kotlin.collections.first
import kotlin.collections.toTypedArray

val removeFromThing = listOf("hidden(\\w)?").map { Regex(it, RegexOption.IGNORE_CASE) }
private val modRegex = Regex("^mod[ _]")
private val re_notWordOrSpace = Regex("[^\\s\\w]")

fun String.sanitizeNamedAttributeName(): String {
	return this.replace(modRegex, "").replace("SPELL", "spell").replace(":", " ").replace(re_notWordOrSpace, "")
}

val forceNamedAttributeTypes = mapOf(
	"building cost reduction" to "Int"
)

/**
 * set of variable names to turn from `it` to `mult${it.capitalize}`
 */
val addMultPrefix = mutableSetOf(
	"dmgFalloff",
	"healingReceived",
	"reloadTime"
)

val overrideAutogeneratedScopeNames = mapOf(
	"MedigunChargeIsCritBoost" to "UberchargeType"
)

/**
 * map of "scope name" to "regex to remove from thing"
 */
val stripFromScopeMembersNames = mutableMapOf(
	"Meter" to "itemMeter",
	"OnKill" to "onKill",
	"OnHit" to "onHit",
	"Projectiles" to "projectiles?"
)

val dontMergeClassMembersIntoHierarchyCompanion = setOf(
	"AirblastAttributes",
	"FlamesAttributes"
)

val overrideAutogenVarNames: MutableMap<String, String> = mutableMapOf(
	"fixedShotPattern" to "fixedWeaponSpread",
	"multSpreadScalesConsecutive" to "spreadIncreasesOnConsecutiveShots",
	"spread" to "weaponSpread",
	"panicAttackNegative" to "multSpreadAsHealthDecreases",
	"noReloadDisplayOnly" to "noReload_displayOnly",
	"sanguisuge" to "gainHealthOnBackstab",
	"medigunChargeIsCritBoost" to "giveCrits",
	"medigunChargeIsResists" to "giveResistanceType",
	"usesAmmoWhileAiming" to "spinupAmmoDrain",
	"minigunNoSpinSounds" to "silentBarrel",
	"botCustomJumpParticle" to "customJumpParticle",
	"botMedicUberHealthThreshold" to "medicUberHealthThreshold",
	"botMedicUberDeployDelayDuration" to "medicUberDeployDelayDuration",
	"particleEffectUseHeadOrigin" to "useHeadOrigin",
	"particleEffectVerticalOffset" to "verticalOffset",
	"maxPipebombs" to "maxStickies",
	"halloweenPumpkinExplosions" to "pumpkinBombs",
	"rocketLaunchImpulse" to "canRocketJumpWithExplosion",
	"sentryKilledRevenge" to "canGainRevengeCrits",
	"shovelDamageBoost" to "isEqualizer",
	"shovelSpeedBoost" to "isEscapePlan",
	"sniperNoHeadshots" to "cannotHeadshot",
	"sniperFullChargeDamageBonus" to "fullChargeDamageBonus",
	"sRifleChargeRate" to "chargeRate",
	"sniperOnlyFireZoomed" to "canOnlyFireWhenZoomed",
	"sniperPenetratePlayersWhenCharged" to "penetratesWhenFullyCharged",
	"sniperNoHeadshotWithoutFullCharge" to "cannotHeadshotWithoutFullCharge",
	"sniperCritNoScope" to "canHeadshotUnscoped",
	"explosiveSniperShot" to "explosiveHeadshotLevel",
	"ammoGivesCharge" to "ammoPacksGiveDemoknightCharge",
	"critModDisabled" to "multRandomCritChance",
	"engineerBuildingTeleportingPickup" to "buildingRescueMetalCost",
	"countsAsAssisterIsSomeKindOfPetThisUpdateIsGoingToBeAwesome" to "countsAsAssister",
	"backstabShield" to "blocksBackstab",
	"activeHealthDegen" to "passiveHealthRegen",
	"healthOnRadiusDamage" to "healOnHit_radial",
	"multHealthFromhealersPenaltyActive" to "multHealthFromHealersWhileActive",
	"overhealFillRateReduced" to "multOverhealFillRate",
	"maxhealthDrainRate" to "maxHealthDrainedWhileActive",
	"dmgBonusWhileHalfDead" to "multDmgWhileHalfDead",
	"dmgPenaltyWhileHalfAlive" to "multDmgWhileHalfAlive",
	"damageAppliesToSappers" to "canDamageSappers",
	"restoreHealthOnKill" to "restoreHealthPercent",
	"healOnKill" to "restoreHealthFlat",
	"upgradeRateDecrease" to "metalAddedPerHit",
	"engyBuildingHealthBonus" to "multBuildingHealth",
	"buildingCostReduction" to "multConstructionCost",
	"engineerSentryBuildRateMultiplier" to "multBuildRate",
	"modBuffDuration" to "multBuffDuration",
	"multHealthFrompacks" to "multHealthFromPacks",
	"multHealthFromhealers" to "multHealthFromHealers",
	"airblastVulnerabilityMultiplier" to "multAirblastVulnerability",
	"airblastVerticalVulnerabilityMultiplier" to "multAirblastVerticalVulnerability",
	"aimingKnockbackResistance" to "multKnockbackWhileAiming",
	"zombiezombiezombiezombie" to "useZombieSkin",
	"rageGivingScale" to "multRageGained",
	"hypeOnDamage" to "gainHypeOnDamage",
	"loseHypeOnTakeDamage" to "hypeLostPerDamageTaken",
	"multDmgtakenFromExplosions" to "multDmgTakenExplosives",
	"multSpreadScale" to "multBulletSpread"
)


/**
 * A less brittle map, using the actual attribute name
 */
val overrideNamedAttributeVarNames = mapOf(
	"bullets per shot bonus" to "modBulletsPerShot",
	"build rate bonus" to "multBuildRate",
	"metal_pickup_decreased" to "multMetalPickup",
	"engy sentry radius increased" to "multRadius",
	"engy sentry fire rate increased" to "multFireRate",
	"engy disposable sentries" to "numDisposableSentries",
	"engy dispenser radius increased" to "multRadius",
	"engineer teleporter build rate multiplier" to "multBuildRate",
	"mod teleporter cost" to "multMetalCost",
	"SET BONUS: cloak blink time penalty" to "multBlinkTime",
	"SET BONUS: quiet unstealth" to "quietDecloak",
	"headshot damage increase" to "multHeadshotDamage",
	"reduced_healing_from_medics" to "multHealingFromMedics",
	"hidden maxhealth non buffed" to "addMaxHealth_nonBuffed",
	"charge recharge rate increased" to "multRechargeRate",
	"upgrade rate decrease" to "multMetalGivenOnHit",
	"engy building health bonus" to "multBuildingHealth",
	"kill forces attacker to laugh" to "forceLaugh",
	"dmg taken increased" to "multDmgTaken",
	"SET BONUS: dmg from sentry reduced" to "multDmgTakenSentry",
	"mult_spread_scale_first_shot" to "multBulletSpreadFirstShot",
	"damage bonus while disguised" to "multDmgWhileDisguised",
	"mod medic healed damage bonus" to "multDmgPerHealer",
	"accuracy scales damage" to "accuracyDamageMultiplier"
)

/**
 * "varName of scope" to "map of old var names to new var names"
 *
 * if the old var name is null, that sets the name of the scope
 *
 * if the old var name is [Unit], that denotes that the default attribute for the scope should be
 */
val overrideScopeVarNames: Map<String, Map<Any?, Any>> = mapOf(
	"MultDmgtakenFromCrit" to mapOf(
		null to "multDmgTakenCrits",
		"dmgTakenFromCritReduced" to "bonus",
		"dmgTakenFromCritIncreased" to "penalty",
		"setBonusDmgTakenFromCritReducedSetBonus" to "bonus_setBonus",
		Unit to "bonus"
	),
	"MultDmgtakenFromFire" to mapOf(
		null to "multDmgTakenFire",
		"dmgTakenFromFireReduced" to "bonus",
		"dmgTakenFromFireIncreased" to "penalty",
		"setBonusDmgTakenFromFireReducedSetBonus" to "bonus_setBonus",
		Unit to "bonus"
	),
	"MultDmgtakenFromBullets" to mapOf(
		null to "multDmgTakenBullets",
		"dmgTakenFromBulletsReduced" to "bonus",
		"dmgTakenFromBulletsIncreased" to "penalty",
		"setBonusDmgTakenFromBulletsIncreased" to "penalty_setBonus",
		"cardDmgTakenFromBulletsReduced" to "penalty_card",
		Unit to "bonus"
	),
	"ModJumpHeight" to mapOf(
		null to "multJumpHeight",
		"increasedJumpHeight" to "standard",
		"majorIncreasedJumpHeight" to ("descOnWearer" to listOf("Shows in the \"On Wearer:\" list in the loadout screen. Note that _all_ attributes apply on wearer unless [provideOnActive][WeaponBaseAttributes.SwapWeaponsAttributes.provideOnActive] is set.")),
		"halloweenIncreasedJumpHeight" to "halloween",
		Unit to "standard"
	),
	"MultPlayerMovespeed" to mapOf(
		null to "multMoveSpeed",
		"moveSpeedBonus" to "bonus",
		"moveSpeedPenalty" to "penalty",
		"majorMoveSpeedBonus" to ("bonus_descOnWearer" to listOf("Shows in the \"On Wearer:\" list in the loadout screen. Note that _all_ attributes apply on wearer unless [provideOnActive][WeaponBaseAttributes.SwapWeaponsAttributes.provideOnActive] is set.")),
		"setBonusMoveSpeedSetBonus" to "bonus_setBonus",
		"cardMoveSpeedBonus" to "bonus_card",
		Unit to "bonus"
	),
	"MultPlayerAimingMovespeed" to mapOf(
		"aimingMovespeedIncreased" to "bonus",
		"aimingMovespeedDecreased" to "penalty",
		"sniperAimingMovespeedDecreased" to "penalty_sniper"
	),
	"AddMaxhealth" to mapOf(
		null to "addMaxHealth",
		"max health additive bonus" to "bonus",
		"max health additive penalty" to "penalty",
		"SET BONUS: max health additive bonus" to "setBonus",
		Unit to "bonus"
	),
	"GenerateRageOnDmg" to mapOf(
		"generateRageOnDamage" to "standard",
		"engineerRageOnDmg" to "buildingRescue",
		Unit to "standard"
	),
	"MaxAmmo" to mapOf(
		null to "multMaxAmmo",
		"multMaxammoPrimary" to "primary",
		"multMaxammoSecondary" to "secondary",
		"multMaxammoMetal" to "metal",
		"maxammo grenades1 increased" to "batBalls"
	),
	"ProjectilePenetration" to mapOf(
		"projectilePenetration" to "projectiles",
		"projectilePenetrationHeavy" to "bullets",
		Unit to "projectiles"
	),
	"ChargeTurnControl" to mapOf(
		null to "multChargeTurnControl",
		"multChargeTurnControl" to "standard",
		"fullChargeTurnControl" to "fullTurnControl",
		Unit to "standard"
	),
	"AddHealthRegen" to mapOf(
		null to "healthRegenPerSecond",
		"healthRegen" to "regen",
		"healthDrain" to "drain",
		"setBonusHealthRegenSetBonus" to "regen_setBonus",
		"healthDrainMedic" to "drain_medic",
		"cardHealthRegen" to "card",
		Unit to "regen"
	)
)

private val attrClass_to_createScopeForItsItems: Map<String, List<NamedAttribute>.() -> List<ISortedNamedAttribute>> by lazy {
	fun List<NamedAttribute>.select(attr: String): NamedAttribute = first { it.attrName == attr }
	
	mapOf(
		"set_buff_type" to {
			this // flatten entries to premade subgroup
		},
		"or_crit_vs_playercond" to {
			listOf(
				// general
				select("crit vs burning players").copy(inGameDesc=null).apply {
					varName = "critVsConditions"
				},
				// specifics
				select("crit vs burning players").apply {
					codec = FakeCodec("Boolean", "{ if (it) EnumSetOrCodec()(EnumSet.of(TFCritCondition.Burning)) else null }")
				},
				select("crit vs disguised players").apply {
					codec = FakeCodec("Boolean", "{ if (it) EnumSetOrCodec()(EnumSet.of(TFCritCondition.Disguised)) else null }")
				}
			)
		},
		"mult_dmg" to {
			listOf(
				PenaltyBonus(
					bonus = select("damage bonus"),
					penalty = select("damage penalty"),
					neutral = select("CARD: damage bonus"),
					hidden = select("damage bonus HIDDEN")
				).apply {
					varName = "multDmg"
				}
			)
		},
		"mult_postfiredelay" to {
			listOf(
				PenaltyBonus(
					bonus = select("fire rate bonus"),
					penalty = select("fire rate penalty"),
					hidden = PenaltyBonus(
						bonus = select("fire rate bonus HIDDEN"),
						penalty = select("fire rate penalty HIDDEN")
					),
					neutral = select("melee attack rate bonus")
				).apply {
					notes += first().notes
					varName = "multPostFireDelay"
				}
			)
		},
	)
}

/** Scopename to description lines */
val extraScopeDescriptions = mapOf(
	"Afterburn" to listOf("Attributes related to afterburn."),
	"Ammo" to listOf("Attributes related to max ammo, clip-size, and resupply."),
	"Buildings" to listOf("Attributes related to moving, constructing, and interacting with the Engineer's buildings."),
	"Crits" to listOf("Attributes related to dealing or preventing critical hits and mini-crits."),
	"Damage" to listOf(
		"Multipliers governing the damage you deal to different targets.",
		"For damage _taken_, see [resistance]."
	),
	"DemoCharge" to listOf(
		"Attributes governing the Demoknight's shield-charge.",
		"Some of these attributes are hardcoded to only work on the Demoman. These are noted in their documentation."
	),
	"Firing" to listOf("Attributes governing rate-of-fire."),
	"HealthAndHealing" to listOf("Attributes related to the player's HP stat and healing players."),
	"KnockbackReceived" to listOf("Attributes governing how much you are pushed when hit by different push sources."),
	"Meta" to listOf("Attributes related to the scoreboard, killfeed, HuD, item descriptions, and interactions with the wider game-state. (including capture rate)"),
	"Meter" to listOf("Attributes related to rage and items that recharge on a meter/timer."),
	"Movement" to listOf("Attributes governing the player's move-speed, jump height, swimming, air-strafing capabilities, and all things mobility-related."),
	"Heads" to listOf(
		"Attributes related to the collection and passive effects of \"heads\".",
		"While originally made for the Eyelander, this stat is used by many other weapons that track players hit or killed: the Vita-Saw, the Bazaar Bargain, etc.",
		"For \"revenge crits\", like the Frontier Justice, Manmelter, and Diamondback, see [revengeCrits]."
	),
	"OnHit" to listOf(
		"Attributes governing what happens when you hit another player, such as applying conditions or debuffs.",
		"@see onKill"
	),
	"OnKill" to listOf(
		"Attributes governing what happens when you kill another player, usually applying bonuses to yourself.",
		"@see onHit"
	),
	"Projectiles" to listOf(
		"All attributes governing what projectile or bullet this weapon can fire, and how that projectile or bullet acts once fired.",
		"Each type of projectile also has a subcategory with every attribute it checks for on the gun that fired it.",
	),
	"Reloading" to listOf("Attributes governing either the time taken to reload a weapon's magazine or the cooldown time for weapons that draw directly from reserve ammo like the Sniper Rifle and Flare Gun."),
	"Resistance" to listOf(
		"Attributes governing how much damage the player takes from various sources.  Also includes the passive and active effects of the Vaccinator on the user.",
		"For outgoing damage, see [damage]."
	),
	"RevengeCrits" to listOf(
		"Attributes governing the collection of \"Revenge Crits\", guaranteed criticals gained by fulfilling certain requirements.",
		"It should be noted that for the most part, these attributes just state whether or not a weapon CAN gain revenge crits. Actually _using_ them is bound to the weapon type, not any attribute.",
		"For the collection and usage of \"heads\", see [heads]."
	),
	"StatusEffects" to listOf(
		"Attributes related to Mad Milk, Jarate, and Gas.",
		"This will be empty for most weapons unless a mod adds something.  Notably, \"explode on ignite\" is available for all weapons."
	),
	"Taunting" to listOf("Attributes governing taunt speed and the effects of taunts."),
	"WhenHit" to listOf(
		"Attributes governing what happens when this player is hit by an enemy.",
		"For what happens when _this player_ hits an enemy, see [onHit] and [onKill]."
	),
	"Ragdolls" to listOf("Attributes governing ragdolls, gibs, and statues."),
	"Disguise" to listOf("Attributes related to disguising."),
	"SwapWeapons" to listOf("Attributes governing weapon deploy/holster speed, things that activate when a weapon is deployed, and whether a player can swap weapons at all."),
	"Flames" to listOf("Attributes controlling how flames emitted by the flamethrower move and reflect."),
	"Airblast" to listOf("Attributes governing the flamethrower's airblast, including [what it's allowed to do][AirblastAttributes.functionalityFlags], the [direction it pushes][AirblastAttributes.reverseAirblast], and whether it [flings the wielder forward][AirblastAttributes.airblast_dashes]."),
) + mapOf(

)



fun NamedAttributeScope.overrideScopeVarNames() {
	val overrides = overrideScopeVarNames[this.scopeName]
	                ?: return;
	
	this.attrs.forEach { attr ->
		(overrides[attr.varName] ?: (attr as? NamedAttribute)?.attrName?.let { overrides[it] })?.let {
			when (it) {
				is String -> attr.varName = it
				is Pair<*, *> -> {
					attr.varName = it.first as String
					attr.notes += it.second as List<String>
				}
				else -> {
					null
				}
			}
		} ?: System.err.println("No remap found for ${this.clsname}.${attr.varName}")
	}
	
	overrides[null]?.let {
		if (it is String)
			this.varName = it
		else if (it is Pair<*, *>) {
			this.varName = it.first as String
			this.notes += it.second as List<String>
		}
	}
	
	overrides[Unit]?.let { defaultAttribute ->
		this.defaultAttribute = this.attrs.firstOrNull { it.varName == defaultAttribute }
		                        ?: return System.err.println("No attribute matching $defaultAttribute found in ${this.clsname}")
	}
}

fun <T : ISortedNamedAttribute> T.postprocessRecursive(): T = apply {
	this.varName = this.varName.overrideVarName()
	
	when (this) {
		is NamedAttribute -> {
			overrideNamedAttributeVarNames[this.attrName]?.let {
				this.varName = it
			}
			
			forceNamedAttributeTypes[this.attrName]?.let {
				this.forceType = it
			}
		}
		is PenaltyBonus -> {
			extraScopeDescriptions[this.varName]?.let {
				this.innateDescription += it
			}
		}
		is NamedAttributeScope -> {
			extraScopeDescriptions[this.scopeName]?.let {
				this.innateDescription += it
			}
			
			this.overrideScopeVarNames()
			
			stripFromScopeMembersNames[scopeName]?.let { toStrip ->
				attrs.forEach {
					it.varName = it.varName.removeFromCamelCase(toStrip)
				}
			}
			
			this.attrs.forEach {
				it.postprocessRecursive()
			}
		}
	}
}


/**
 * Create some combined representation for these attributes in the same attribute class.
 *
 * This is here because we need to override the name with something hand-picked for the scope in [attrClass_to_createScopeForItsItems]
 */
fun fabricateScope(attrClass: String, attrsOfSameClass: List<NamedAttribute>): List<ISortedNamedAttribute> {
	fun NamedAttributeScope.overrideAutogen() = apply {
		this.scopeName = overrideAutogeneratedScopeNames[scopeName]
		                 ?: scopeName.removeBonusPenaltyHiddenStuff()
	}
	
	fun makeDefaultScope(clsName: String): NamedAttributeScope {
		return NamedAttributeScope(clsName.camelCase().capitalize(), *attrsOfSameClass.toTypedArray())
	}
	
	fun groupHiddenItemsIntoPenaltyBonus(allHidden: List<NamedAttribute>): ISortedNamedAttribute {
		return when (allHidden.size) {
			1 -> allHidden.single()
			// Make hidden items into a nested PenaltyBonus
			else -> allHidden.groupBy { it.effectType }.let {
				it.values.firstOrNull { it.size > 1 }?.let {
					error("Too many values: $it")
				}
				PenaltyBonus(
					penalty=it[EffectType.Negative]?.single(),
					bonus=it[EffectType.Positive]?.single(),
					neutral=it[EffectType.Neutral]?.single(),
				)
			}
		}
	}
	
	
	//
	attrClass_to_createScopeForItsItems[attrClass]?.let { ctor ->
		return ctor(attrsOfSameClass)
	}
	
	
	val isPos = 0; val isNeg = 1; val isNeu = 2; val isHidden = 3
	val groupedByPosNegNeutral = attrsOfSameClass.groupBy {
		when {
			it.isHidden == true -> isHidden
			else -> when (it.effectType) {
				EffectType.Positive -> isPos
				EffectType.Negative -> isNeg
				EffectType.Neutral -> isNeu
			}
		}
	}
	// If we have multiple bonuses or multiple penalties and they're not just hidden, we should have assigned a custom scope.
	// Fallthrough to just making a default scope.
	if (groupedByPosNegNeutral.size == 1 || groupedByPosNegNeutral.any { it.key != isHidden && it.value.size > 1 }) {
		return listOf(makeDefaultScope(attrClass).overrideAutogen())
	}
	
	/*
	Variants:
	- If there's only 1 attribute in the class, just return that attribute
	- If there's only 1 positive/negative/neutral + some hiddens -> Vis
	- Else if there's some combination of positive, negative, neutral, hidden, make it a PenaltyBonus
		- If there are multiple hidden, make the hidden ALSO a PenaltyBonus
	 */
	if (groupedByPosNegNeutral.size == 1) {
		return attrsOfSameClass // if they're all one type, just do them separately
	}
	
	return when (groupedByPosNegNeutral.size) {
		2 -> {
			if (isHidden in groupedByPosNegNeutral) { // if there's just a hidden and a visible, do Vis
				val notHidden = groupedByPosNegNeutral.entries.first { it.key != isHidden }.value.single()
				val hidden = groupedByPosNegNeutral[isHidden]!!.let { allHidden ->
					groupHiddenItemsIntoPenaltyBonus(allHidden)
				}
				
				Vis(notHidden, hidden, attrClass)
			} else {
				// Else it's a custom PenaltyBonus
				PenaltyBonus(
					groupedByPosNegNeutral[isNeg]?.single(),
					groupedByPosNegNeutral[isPos]?.single(),
					groupedByPosNegNeutral[isNeu]?.single(),
				)
			}
		}
		else -> {
				PenaltyBonus(
					groupedByPosNegNeutral[isNeg]?.single(),
					groupedByPosNegNeutral[isPos]?.single(),
					groupedByPosNegNeutral[isNeu]?.single(),
					groupedByPosNegNeutral[isHidden]?.let { groupHiddenItemsIntoPenaltyBonus(it) }
				)
		}
	}.let {
		it.varName = attrClass.camelCase()
		listOf(it)
	}.onEach {
		if (it is NamedAttributeScope) {
			it.overrideAutogen()
		}
	}
}

fun String.overrideVarName(): String {
	if (this in addMultPrefix) {
		return "mult" + this.replaceFirstChar { it.uppercaseChar() }
	}
	return (overrideAutogenVarNames[this] ?: this)
}


val removeFromPBName = listOf("decreased?", "lower(?:ed)?", "increased?", "bonus", "penalty").map { Regex(it, RegexOption.IGNORE_CASE) }
val attrToSelector = mapOf(
	"Fists" to mapOf("fists have radial buff" to 1),
	"Invis" to mapOf(
		"set cloak is movement based" to 1,
		"set cloak is feign death" to 2
	),
	"Bat" to mapOf(
		"mod bat launches balls" to 1,
		"mod bat launches ornaments" to 2
	),
	"Revolver" to mapOf("revolver use hit locations" to 1),
	"Shovel" to mapOf(
		"mod shovel damage boost" to 1,
		"mod shovel speed boost" to 2
	),
	"Lunchbox" to mapOf(
		"lunchbox adds maxhealth bonus" to 1,
		"lunchbox adds minicrits" to 2
	),
	"SniperRifle" to mapOf("sniper no headshots" to 1),
	"Knife" to mapOf("set icicle knife mode" to 3),
	"FlareGun" to mapOf("mod flaregun fires pellets with knockback" to 3)
)
val customCodecs = mapOf(
	"or_crit_vs_not_playercond" to FakeCodec("EnumSet<TFCritCondition>", "EnumSetOrCodec()"),
	"or_crit_vs_playercond" to FakeCodec("EnumSet<TFCritCondition>", "EnumSetOrCodec()"),
)

fun String.removeBonusPenaltyHiddenStuff(): String {
	return (removeFromPBName + removeFromThing).fold(this) { it, re -> it.removeFromCamelCase(re) }
}


/**
 * Cache conversion of stuff like `"itemMeter"` to `Regex("[Ii]temMeter")`
 * so we can possibly match the thing in the middle of a word
 */
private val regexCache = HashMap<String, Regex>()

fun String.removeFromCamelCase(toRemove: String): String {
	val re = regexCache.computeIfAbsent(toRemove) {
		Regex(it.replaceFirstChar { c ->
			val alt = if (c.isUpperCase()) c.lowercaseChar() else c.uppercaseChar()
			"[$c$alt]"
		})
	}
	
	return this.removeFromCamelCase(re)
}

fun String.removeFromCamelCase(toRemove: Regex): String {
	if (toRemove.matchesAt(this, 0)) {
		return toRemove.replaceFirst(this, "")
			.replaceFirstChar { it.lowercaseChar() } // make sure beginning isn't left capitalized
	}
	
	return this.replace(toRemove, "")
}